version: 1.0.{build}
image: Visual Studio 2015
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
test:
  categories:
    except:
    - InternetRequired
    - CloundIgnore